server:
  port: 8210

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order?serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml


eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10   # 从Eureka中获取的服务列表多久更新一次
    service-url:
      defaultZone: http://localhost:8120/eureka

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 1500
  ReadTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1



