package com.wei.generator.entity;

/**Auto Generated By Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Table(name = "bamboo_user")
public class BambooUserEntity {

     public static final String FIELD_ID = "id";
     public static final String FIELD_USERNAME = "username";
     public static final String FIELD_PASSWORD = "password";
     public static final String FIELD_SEX = "sex";

     @Id
     @GeneratedValue
     private Long id;

     @NotEmpty
     @Length(max = 255)
     private String username;

     @NotEmpty
     @Length(max = 255)
     private String password;

     @NotEmpty
     @Length(max = 1)
     private String sex;

}