package com.wei.generator.common.utils;

import com.wei.generator.common.enumeration.FileType;
import com.wei.generator.model.ColumnModel;
import com.wei.generator.model.TableModel;
import com.wei.generator.model.TempleModel;
import com.wei.generator.model.XmlColumnModel;
import com.wei.generator.model.request.GeneratorRequestModel;
import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import org.apache.commons.lang.StringUtils;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import javax.servlet.http.HttpServletRequest;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class FileUtils {

    private static List<String> allClassFiles = new ArrayList<>();
    private static List<String> allXmlFiles = new ArrayList<>();
    private static List<String> allHtmlFiles = new ArrayList<>();

    private static String columnToCamel(String columnName) {
        Pattern linePattern = Pattern.compile("_(\\w)");
        columnName = columnName.toLowerCase();
        Matcher matcher = linePattern.matcher(columnName);
        StringBuffer sb = new StringBuffer();
        while (matcher.find()) {
            matcher.appendReplacement(sb, matcher.group(1).toUpperCase());
        }
        matcher.appendTail(sb);
        String s = sb.toString();
        return s;
    }

    public static String camelToColumn(String columnNameCamel){
        return columnNameCamel.replaceAll("[A-Z]", "_$0").toLowerCase();
    }

    public static void createDtoFile(TableModel table, GeneratorRequestModel generatorInfo) throws IOException {
        // key 是否需要引入相对包
        boolean needUtil = false;
        boolean needNotNull = false;
        boolean needNotEmpty = false;

        String name = generatorInfo.getDtoName().substring(0, generatorInfo.getDtoName().indexOf("."));
        String projectPath = generatorInfo.getProjectPath();
        String parentPackagePath = generatorInfo.getParentPackagePath();
        String packagePath = generatorInfo.getPackagePath();
        String directory = projectPath + "/src/main/java/" + parentPackagePath + "/" + packagePath + "/dto/"
                + generatorInfo.getDtoName();

        File file = new File(directory);
        createFileDir(file);
        file.createNewFile();
        List<ColumnModel> columns = table.getColumns();
        // 判断是否需要引入包
        for (ColumnModel column : columns) {
            switch (column.getJdbcType().toUpperCase()) {
                case "DATE":
                case "TIMESTAMP":
                case "DATETIME":
                case "TIME":
                    column.setJavaType("Date");
                    column.setJdbcType("DATE");
                    needUtil = true;
                    break;
                case "BIGINT":
                case "INT":
                case "INTEGER":
                case "DECIMAL":
                case "TINYINT":
                    column.setJavaType("Long");
                    column.setJdbcType("DECIMAL");
                    break;
                case "DOUBLE":
                    column.setJavaType("Double");
                    column.setJdbcType("DECIMAL");
                    break;
                case "NUMBER":
                case "FLOAT":
                    column.setJavaType("Float");
                    column.setJdbcType("DECIMAL");
                    break;
                default:
                    column.setJavaType("String");
                    column.setJdbcType("VARCHAR");
                    break;
            }
            if (column.isNotNull()) {
                needNotNull = true;
            } else if (column.isNotEmpty()) {
                needNotEmpty = true;
            }
        }
        // 生成属性
        StringBuilder sb = new StringBuilder();
        String dir1 = parentPackagePath + "/" + packagePath + "/dto";
        dir1 = dir1.replaceAll("/", ".");
        sb.append("package " + dir1 + ";\r\n\r\n");
        sb.append("/**Auto Generated By Hap Code Generator**/\r\n");
        sb.append("import javax.persistence.GeneratedValue;\r\n");
        sb.append("import javax.persistence.Id;\r\n");
        sb.append("import com.hand.hap.mybatis.annotation.ExtensionAttribute;\r\n");
        sb.append("import org.hibernate.validator.constraints.Length;\r\n");
        sb.append("import javax.persistence.Table;\r\n");
//        String d = BaseDTO.class.getName();
//        sb.append("import " + d + ";\r\n");
        if (needUtil) {
            sb.append("import java.util.Date;\r\n");
        }
        if (needNotNull) {
            sb.append("import javax.validation.constraints.NotNull;\r\n");
        }
        if (needNotEmpty) {
            sb.append("import org.hibernate.validator.constraints.NotEmpty;\r\n");
        }
//        if (table.isMultiLanguage()) {
//            String s1 = MultiLanguageField.class.getName();
//            String s2 = MultiLanguage.class.getName();
//            sb.append("import " + s1 + ";\r\n");
//            sb.append("import " + s2 + ";\r\n");
//            sb.append("\r\n\r\n@MultiLanguage\r\n");
//        }
        sb.append("@ExtensionAttribute(disable=true)\r\n");
        sb.append("@Table(name = " + "\"" + table.getName() + "\")\r\n");
        sb.append("public class " + name + " extends BaseDTO {\r\n\r\n");

        //生成filed
        for(ColumnModel column : columns){
            String filed1=  "     public static final String FIELD_" + column.getName().toUpperCase() + " = \"" + columnToCamel(column.getName()) + "\";\r\n";
            sb.append(filed1);
        }
        sb.append("\r\n\r\n");

        // 生成属性
        for (ColumnModel column : columns) {
            if (column.isId()) {
                sb.append("     @Id\r\n     @GeneratedValue\r\n");
            } else {
                if (column.isNotEmpty()) {
                    sb.append("     @NotEmpty\r\n");
                } else if (column.isNotNull()) {
                    sb.append("     @NotNull\r\n");
                }
                if (column.getJavaType().equalsIgnoreCase("String")) {
                    sb.append("     @Length(max = ");
                    sb.append(column.getColumnLength() + ")\r\n");
                }
            }
            if (column.isMultiLanguage()) {
                sb.append("     @MultiLanguageField\r\n");
            }
            String str = "     private " + column.getJavaType() + " " + columnToCamel(column.getName()) + ";";
            if (!StringUtils.isEmpty(column.getRemarks())) {
                str += " //" + column.getRemarks();
            }
            str += "\r\n\r\n";
            sb.append(str);
        }

        // 生成get 和 set方法
        sb.append("\r\n");
        for (ColumnModel column : columns) {
            String name1 = columnToCamel(column.getName());
            String name2 = name1.substring(0, 1).toUpperCase() + name1.substring(1);
            sb.append("     public void set" + name2 + "(" + column.getJavaType() + " " + name1 + "){\r\n");
            sb.append("         this." + name1 + " = " + name1 + ";\r\n");
            sb.append("     }\r\n\r\n");
            sb.append("     public " + column.getJavaType() + " get" + name2 + "(){\r\n");
            sb.append("         return " + name1 + ";\r\n");
            sb.append("     }\r\n\r\n");
        }
        sb.append("     }\r\n");

        PrintWriter p = new PrintWriter(new OutputStreamWriter(new FileOutputStream(file), "utf-8"));
        p.write(sb.toString());
        p.close();

    }

    public static void createFtlInfoByType(FileType type, TableModel table, GeneratorRequestModel generatorInfo)
            throws IOException, TemplateException {
        String projectPath = generatorInfo.getProjectPath();
        String parentPackagePath = generatorInfo.getParentPackagePath();
        String packagePath = generatorInfo.getPackagePath();
        String htmlModelName = generatorInfo.getHtmlModelName();
        String pac = parentPackagePath + "/" + packagePath;
        TempleModel info = new TempleModel();
        String directory = null;
        List<String> importPackages = new ArrayList<>();
        if (type == FileType.Controller) {
            directory = projectPath + "/src/main/java/" + pac + "/controllers/" + generatorInfo.getControllerName();
            importPackages.add("org.springframework.stereotype.Controller");
//            importPackages.add(BaseController.class.getName());
//            importPackages.add(IRequest.class.getName());
//            importPackages.add(ResponseData.class.getName());
        } else if (type == FileType.Mapper) {
            directory = projectPath + "/src/main/java/" + pac + "/mapper/" + generatorInfo.getMapperName();
            importPackages.add("com.hand.hap.mybatis.common.Mapper");
        } else if (type == FileType.MapperXml) {
            directory = projectPath + "/src/main/resources/" + pac + "/mapper/" + generatorInfo.getMapperXmlName();
        } else if (type == FileType.Service) {
            directory = projectPath + "/src/main/java/" + pac + "/service/" + generatorInfo.getServiceName();
//            importPackages.add(ProxySelf.class.getName());
//            importPackages.add(IBaseService.class.getName());
        } else if (type == FileType.Impl) {
            directory = projectPath + "/src/main/java/" + pac + "/service/impl/" + generatorInfo.getImplName();
//            importPackages.add(BaseServiceImpl.class.getName());
            importPackages.add("org.springframework.stereotype.Service");
        } else if (type == FileType.Html) {
            directory = projectPath + "/src/main/webapp/WEB-INF/view/" + packagePath + "/"
                    + generatorInfo.getHtmlName();
        }
        pac = pac.replaceAll("/", ".");
        info.setPackageName(pac);
        info.setDir(directory);
        info.setProjectPath(projectPath);
        info.setImportName(importPackages);
        info.setHtmlModelName(htmlModelName);
        List<ColumnModel> columns = table.getColumns();

        List<XmlColumnModel> columnsInfos = new ArrayList<>();

        for (ColumnModel column : columns) {
            XmlColumnModel columnsInfo = new XmlColumnModel();
            columnsInfo.setTableColumnsName(columnToCamel(column.getName()));
            columnsInfo.setDBColumnsName(column.getName());
            columnsInfo.setJdbcType(column.getJdbcType());
            columnsInfos.add(columnsInfo);
        }
        info.setColumnsInfo(columnsInfos);
        createFtl(info, type, generatorInfo);
    }

    public static void createFtl(TempleModel ftlInfo, FileType type, GeneratorRequestModel generatorInfo)
            throws IOException, TemplateException {

        Configuration cfg = new Configuration(Configuration.DEFAULT_INCOMPATIBLE_IMPROVEMENTS);
        Template template = null;
        Map<String, Object> map = new HashMap<String, Object>();
        HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes())
                .getRequest();
        cfg.setServletContextForTemplateLoading(request.getServletContext(), "WEB-INF/view/generator/ftl");

        if (type == FileType.Controller) {
            template = cfg.getTemplate("controllers.ftl");
        } else if (type == FileType.MapperXml) {
            template = cfg.getTemplate("mapperxml.ftl");
        } else if (type == FileType.Mapper) {
            template = cfg.getTemplate("mapper.ftl");
        } else if (type == FileType.Service) {
            template = cfg.getTemplate("service.ftl");
        } else if (type == FileType.Impl) {
            template = cfg.getTemplate("impl.ftl");
        } else if (type == FileType.Html) {
            template = cfg.getTemplate(ftlInfo.getHtmlModelName());
        }
        if (null != template) {
            template.setEncoding("UTF-8");
            File file = new File(ftlInfo.getDir());
            createFileDir(file);
            OutputStream out = new FileOutputStream(file);
            map.put("package", ftlInfo.getPackageName());
            map.put("import", ftlInfo.getImportName());
            map.put("name", ftlInfo.getFileName());
            map.put("dtoName", generatorInfo.getDtoName().substring(0, generatorInfo.getDtoName().indexOf('.')));
            map.put("controllerName",
                    generatorInfo.getControllerName().substring(0, generatorInfo.getControllerName().indexOf('.')));
            map.put("implName", generatorInfo.getImplName().substring(0, generatorInfo.getImplName().indexOf('.')));
            map.put("serviceName",
                    generatorInfo.getServiceName().substring(0, generatorInfo.getServiceName().indexOf('.')));
            map.put("mapperName", generatorInfo.getMapperName().substring(0, generatorInfo.getMapperName().indexOf('.')));
            map.put("xmlName",
                    generatorInfo.getMapperXmlName().substring(0, generatorInfo.getMapperXmlName().indexOf('.')));
            map.put("columnsInfo", ftlInfo.getColumnsInfo());
            String url = generatorInfo.getTargetName().toLowerCase();
            if (url.endsWith("_b")) {
                url = url.substring(0, url.length() - 2);
            }
            url = url.replaceAll("_", "/");
            map.put("queryUrl", "/" + url + "/query");
            map.put("submitUrl", "/" + url + "/submit");
            map.put("removeUrl", "/" + url + "/remove");
            template.process(map, new OutputStreamWriter(out));
            out.flush();
            out.close();
        }
    }

    // 判断文件目录是否存在不存在则创建
    public static void createFileDir(File file) throws IOException {
        if (!file.getParentFile().exists()) {
            file.getParentFile().mkdirs();
        }
    }

    // 判断文件是否已经存在
    public static int isFileExist(GeneratorRequestModel generatorInfo) {
        int result = 0;
        String classDir = generatorInfo.getProjectPath() + "/src/main/java/" + generatorInfo.getParentPackagePath();
        String xmlDir = generatorInfo.getProjectPath() + "/src/main/resources/" + generatorInfo.getParentPackagePath();
        String htmlDir = generatorInfo.getProjectPath() + "/src/main/webapp/WEB-INF/view";
        getFileList(classDir, classDir, generatorInfo);
        // 判断有没有重复的java文件

        for (String name : allClassFiles) {
            if (name.equals(generatorInfo.getDtoName())) {
                if ("Create".equalsIgnoreCase(generatorInfo.getDtoStatus())) {
                    result = 1;
                    break;
                } else if ("Cover".equalsIgnoreCase(generatorInfo.getDtoStatus())) {
                    File file1 = new File(
                            classDir + "/" + generatorInfo.getPackagePath() + "/dto/" + generatorInfo.getDtoName());
                    if (!file1.exists()) {
                        result = 1;
                        break;
                    }
                }
            }
        }

        if (result == 0) {
            for (String name : allClassFiles) {
                if (name.equals(generatorInfo.getServiceName())) {
                    if ("Create".equalsIgnoreCase(generatorInfo.getServiceStatus())) {
                        result = 2;
                        break;
                    } else if ("Cover".equalsIgnoreCase(generatorInfo.getServiceStatus())) {
                        File file1 = new File(classDir + "/" + generatorInfo.getPackagePath() + "/service/"
                                + generatorInfo.getServiceName());
                        if (!file1.exists()) {
                            result = 2;
                            break;
                        }
                    }
                }
            }
        }

        if (result == 0) {
            for (String name : allClassFiles) {
                if (name.equals(generatorInfo.getImplName())) {
                    if ("Create".equalsIgnoreCase(generatorInfo.getImplStatus())) {
                        result = 3;
                        break;
                    } else if ("Cover".equalsIgnoreCase(generatorInfo.getImplStatus())) {
                        File file1 = new File(classDir + "/" + generatorInfo.getPackagePath() + "/service/impl/"
                                + generatorInfo.getImplName());
                        if (!file1.exists()) {
                            result = 3;
                            break;
                        }
                    }
                }
            }
        }

        if (result == 0) {
            for (String name : allClassFiles) {
                if (name.equals(generatorInfo.getControllerName())) {
                    if ("Create".equalsIgnoreCase(generatorInfo.getControllerStatus())) {
                        result = 4;
                        break;
                    } else if ("Cover".equalsIgnoreCase(generatorInfo.getControllerStatus())) {
                        File file1 = new File(classDir + "/" + generatorInfo.getPackagePath() + "/controllers/"
                                + generatorInfo.getControllerName());
                        if (!file1.exists()) {
                            result = 4;
                            break;
                        }
                    }
                }
            }
        }
        if (result == 0) {
            for (String name : allClassFiles) {
                if (name.equals(generatorInfo.getMapperName())) {
                    if ("Create".equalsIgnoreCase(generatorInfo.getMapperStatus())) {
                        result = 5;
                        break;
                    } else if ("Cover".equalsIgnoreCase(generatorInfo.getMapperStatus())) {
                        File file1 = new File(classDir + "/" + generatorInfo.getPackagePath() + "/mapper/"
                                + generatorInfo.getMapperName());
                        if (!file1.exists()) {
                            result = 5;
                            break;
                        }
                    }
                }
            }
        }

        // 判断有没有重复的xml文件
        if (result == 0) {
            getFileList(xmlDir, xmlDir, generatorInfo);
            for (String name : allXmlFiles) {
                if (name.equals(generatorInfo.getMapperXmlName())) {
                    if ("Create".equalsIgnoreCase(generatorInfo.getMapperXmlStatus())) {
                        result = 6;
                        break;
                    } else if ("Cover".equalsIgnoreCase(generatorInfo.getMapperXmlStatus())) {
                        File file1 = new File(xmlDir + "/" + generatorInfo.getPackagePath() + "/mapper/"
                                + generatorInfo.getMapperXmlName());
                        if (!file1.exists()) {
                            result = 6;
                            break;
                        }
                    }
                }
            }
        }
        // 判断有没有重复的html文件
        if (result == 0) {
            getFileList(htmlDir, htmlDir, generatorInfo);
            for (String name : allHtmlFiles) {
                if (name.equals(generatorInfo.getHtmlName())) {
                    if ("Create".equalsIgnoreCase(generatorInfo.getHtmlStatus())) {
                        result = 7;
                        break;
                    } else if ("Cover".equalsIgnoreCase(generatorInfo.getHtmlStatus())) {
                        File file1 = new File(
                                htmlDir + "/" + generatorInfo.getPackagePath() + "/" + generatorInfo.getHtmlName());
                        if (!file1.exists()) {
                            result = 7;
                            break;
                        }
                    }
                }
            }
        }
        return result;
    }

    // 获取文件夹下所有文件列表
    public static void getFileList(String basePath, String directory, GeneratorRequestModel generatorInfo) {
        File dir = new File(basePath);
        File[] files = dir.listFiles();
        if (files != null) {
            for (int i = 0; i < files.length; i++) {
                String fileName = files[i].getName();
                if (files[i].isDirectory()) {
                    getFileList(files[i].getAbsolutePath(), directory, generatorInfo);
                } else {
                    if (directory.equals(generatorInfo.getProjectPath() + "/src/main/java/"
                            + generatorInfo.getParentPackagePath())) {
                        allClassFiles.add(fileName);
                    } else if (directory.equals(generatorInfo.getProjectPath() + "/src/main/resources/"
                            + generatorInfo.getParentPackagePath())) {
                        allXmlFiles.add(fileName);
                    } else if (directory.equals(generatorInfo.getProjectPath() + "/src/main/webapp/WEB-INF/view")) {
                        allHtmlFiles.add(fileName);
                    }
                }
            }
        }

    }

}
