server:
  port: 8120

spring:
  application:
    name: register

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: {http://localhost:8120/eureka}
    registry-fetch-interval-seconds: 30
  server:
    enable-self-preservation: false

